/*++

Module Name:

    public.h

Abstract:

    This module contains the common declarations shared by driver
    and user applications.

Environment:

    driver and application

--*/

//
// Define an Interface Guid so that apps can find the device and talk to it.
//

DEFINE_GUID (GUID_DEVINTERFACE_HwAccU,
    0x2a20f126,0x1053,0x4b67,0x8b,0x42,0xda,0x34,0x54,0xbb,0x2b,0x55);
// {2a20f126-1053-4b67-8b42-da3454bb2b55}

#define HWACC_TYPE 40000

// The IOCTL function codes from 0x800 to 0xFFF are for customer use.

#define IOCTL_GPD_READ_PORT_UCHAR \
    CTL_CODE( HWACC_TYPE, 0x900, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_READ_PORT_USHORT \
    CTL_CODE( HWACC_TYPE, 0x901, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_READ_PORT_ULONG \
    CTL_CODE( HWACC_TYPE, 0x902, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_WRITE_PORT_UCHAR \
    CTL_CODE(HWACC_TYPE,  0x910, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_GPD_WRITE_PORT_USHORT \
    CTL_CODE(HWACC_TYPE,  0x911, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_GPD_WRITE_PORT_ULONG \
    CTL_CODE(HWACC_TYPE,  0x912, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_GPD_READ_PCI \
    CTL_CODE(HWACC_TYPE,  0x913, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_GPD_WRITE_PCI \
    CTL_CODE(HWACC_TYPE,  0x914, METHOD_BUFFERED, FILE_WRITE_ACCESS)


#define IOCTL_GPD_READ_MEM \
    CTL_CODE( HWACC_TYPE, 0x906, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_READ_MSR \
    CTL_CODE( HWACC_TYPE, 0x907, METHOD_BUFFERED, FILE_READ_ACCESS )


#define IOCTL_GPD_WRITE_MEM \
    CTL_CODE(HWACC_TYPE,  0x916, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_GPD_WRITE_MSR \
    CTL_CODE(HWACC_TYPE,  0x917, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define IOCTL_GPD_MAP_PHYSICAL \
    CTL_CODE( HWACC_TYPE, 0x920, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_UMMAP_PHYSICAL \
    CTL_CODE( HWACC_TYPE, 0x921, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_OPEN_ACPI \
    CTL_CODE( HWACC_TYPE, 0x940, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_EVAL_ACPI \
    CTL_CODE( HWACC_TYPE, 0x950, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_EVAL_ACPI_NO_RETURN \
    CTL_CODE( HWACC_TYPE, 0x951, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_EVAL_ACPI_WITH_PARAMETER \
    CTL_CODE( HWACC_TYPE, 0x952, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_EVAL_ACPI_WITHOUT_PARAMETER \
    CTL_CODE( HWACC_TYPE, 0x953, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_LOAD_AML \
    CTL_CODE( HWACC_TYPE, 0x954, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_UNLOAD_AML \
    CTL_CODE( HWACC_TYPE, 0x955, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_NOTIFY_DEVICE \
    CTL_CODE(HWACC_TYPE, 0x956, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_GPD_GET_NEXT_ACPI_NODE \
    CTL_CODE( HWACC_TYPE, 0x960, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_READ_ACPI_MEMORY \
    CTL_CODE( HWACC_TYPE, 0x961, METHOD_BUFFERED, FILE_READ_ACCESS )
#define IOCTL_GPD_WRITE_ACPI_MEMORY \
        CTL_CODE( HWACC_TYPE, 0x962, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_ENUM_ACPI \
    CTL_CODE( HWACC_TYPE, 0x970, METHOD_BUFFERED, FILE_READ_ACCESS )

#define IOCTL_GPD_BUILD_ACPI \
    CTL_CODE( HWACC_TYPE, 0x970, METHOD_BUFFERED, FILE_READ_ACCESS )